### ISSUE TITLE
Feat: add an optional argument in component command

### ISSUE THREAD

**Issue by iamtabrezkhan** [iamtabrezkhan/awesome-react-generator#1]
Right now, component command only generates a `js` file and a `css` file. An optional argument can be given with command, for instance:
```bash
rg component rfc hello-world --test
```
that will generate a test file also.

**Comment by shadab14meb346** [comment]
Hi, I would like to work on this.

**Comment by iamtabrezkhan** [comment]
Hi @shadab14meb346 

Please go ahead. Let me know if you need any help.
