### ISSUE TITLE
Why "Classes"?

### ISSUE THREAD

**Issue by ecumene** [iamtabrezkhan/awesome-react-generator#17]
In this template:

https://github.com/iamtabrezkhan/awesome-react-generator/blob/3c06c30d3f292ac7eec0efb11be7f5e090e9ae80/lib/classes/component.js#L28

The css module is imported with the name `Classes` In the [CSS modules docs](https://github.com/css-modules/css-modules) they use the word `styles`. Why was the name `Classes` chosen?

To keep consistent with more people's code, I propose we change it to `styles` as a default and add an option to change the name.

**Comment by iamtabrezkhan** [comment]
Hi @ecumene,

I chose the name `Classes` because I personally use this. But yes, what you are proposing makes much more sense. We can change from `Classes` to `styles`.
**Feel free to make a PR for the same**.

// cc @shadab14meb346

**Comment by shadab14meb346** [comment]
I can do the PR for it. By default it will be `styles` but what do you guys suggest the option should be to change the name like an example`--moduleName Classes` or something else.
